package myprojectoescuela;

import javax.swing.JOptionPane;

public class VistaAgencia extends javax.swing.JFrame {

    private Vehiculo vehiculo;
    private ManejadorArchivo manejadorArchivo = new ManejadorArchivo();
    private CRUD crud = new CRUD();
    private int indice = 0;

    /**
     * Creates new form VistaAgencia
     */
    public VistaAgencia() {
        initComponents();

        tbTipoVehiculo.setEnabledAt(0, false);
        tbTipoVehiculo.setEnabledAt(1, false);
        tbTipoVehiculo.setEnabledAt(2, false);

        indice = manejadorArchivo.leerArchivo(crud.getGrupo());
        crud.setIndice(indice);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tbTipoVehiculo = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        bCrearAutomovil = new javax.swing.JButton();
        bActualizarAutomovil = new javax.swing.JButton();
        bEliminarAutomovil = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaToAutomovil = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        tfCaballosFuerza = new javax.swing.JTextField();
        tfNoPuertas = new javax.swing.JTextField();
        bConsultaAutomovil = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        bCrearMotocicleta = new javax.swing.JButton();
        bActualizarMotocicleta = new javax.swing.JButton();
        bEliminarMotocicleta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaToMotocicleta = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfPotencia = new javax.swing.JTextField();
        tfRodada = new javax.swing.JTextField();
        bConsultarMotocicleta = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextAreaToAutoElectrico = new javax.swing.JTextArea();
        bCrearAutoElectrico = new javax.swing.JButton();
        bActualizarAutoElectrico = new javax.swing.JButton();
        bEliminarAutoElectrico = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        tfDuracionBateria = new javax.swing.JTextField();
        bConsultarAutoElectrico = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        tfCaballosFuerza_AutoElectrico = new javax.swing.JTextField();
        tfNoPuerta_AutoElectrico = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfNoSerie = new javax.swing.JTextField();
        tfMarca = new javax.swing.JTextField();
        tfModelo = new javax.swing.JTextField();
        tfColor = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbTipoVehiculo = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        bSalir = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Agencia");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bCrearAutomovil.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bCrearAutomovil.setText("Crear");
        bCrearAutomovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearAutomovilActionPerformed(evt);
            }
        });

        bActualizarAutomovil.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bActualizarAutomovil.setText("Actualizar");
        bActualizarAutomovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActualizarAutomovilActionPerformed(evt);
            }
        });

        bEliminarAutomovil.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bEliminarAutomovil.setText("Eliminar");
        bEliminarAutomovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarAutomovilActionPerformed(evt);
            }
        });

        jTextAreaToAutomovil.setColumns(20);
        jTextAreaToAutomovil.setRows(5);
        jScrollPane2.setViewportView(jTextAreaToAutomovil);

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel6.setText("Caballos de fuerza:");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel7.setText("Número de puertas:");

        bConsultaAutomovil.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bConsultaAutomovil.setText("Consulta");
        bConsultaAutomovil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConsultaAutomovilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNoPuertas))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(bCrearAutomovil)
                                .addGap(20, 20, 20)
                                .addComponent(bActualizarAutomovil)
                                .addGap(18, 18, 18)
                                .addComponent(bEliminarAutomovil)
                                .addGap(18, 18, 18)
                                .addComponent(bConsultaAutomovil))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCaballosFuerza, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfCaballosFuerza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tfNoPuertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bEliminarAutomovil)
                    .addComponent(bCrearAutomovil)
                    .addComponent(bActualizarAutomovil)
                    .addComponent(bConsultaAutomovil))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tbTipoVehiculo.addTab("Automovil", jPanel4);

        bCrearMotocicleta.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bCrearMotocicleta.setText("Crear");
        bCrearMotocicleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearMotocicletaActionPerformed(evt);
            }
        });

        bActualizarMotocicleta.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bActualizarMotocicleta.setText("Actualizar");
        bActualizarMotocicleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActualizarMotocicletaActionPerformed(evt);
            }
        });

        bEliminarMotocicleta.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bEliminarMotocicleta.setText("Eliminar");
        bEliminarMotocicleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarMotocicletaActionPerformed(evt);
            }
        });

        jTextAreaToMotocicleta.setColumns(20);
        jTextAreaToMotocicleta.setRows(5);
        jScrollPane1.setViewportView(jTextAreaToMotocicleta);

        jLabel8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel8.setText("Potencia:");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel9.setText("Rodada:");

        bConsultarMotocicleta.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bConsultarMotocicleta.setText("Consultar");
        bConsultarMotocicleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConsultarMotocicletaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(bCrearMotocicleta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(bActualizarMotocicleta)
                                .addGap(18, 18, 18)
                                .addComponent(bEliminarMotocicleta)
                                .addGap(18, 18, 18)
                                .addComponent(bConsultarMotocicleta)
                                .addGap(0, 64, Short.MAX_VALUE))
                            .addComponent(tfRodada)
                            .addComponent(tfPotencia))))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfRodada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bActualizarMotocicleta)
                    .addComponent(bEliminarMotocicleta)
                    .addComponent(bCrearMotocicleta)
                    .addComponent(bConsultarMotocicleta))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tbTipoVehiculo.addTab("Motocicleta", jPanel5);

        jTextAreaToAutoElectrico.setColumns(20);
        jTextAreaToAutoElectrico.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextAreaToAutoElectrico.setRows(5);
        jScrollPane3.setViewportView(jTextAreaToAutoElectrico);

        bCrearAutoElectrico.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bCrearAutoElectrico.setText("Crear");
        bCrearAutoElectrico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCrearAutoElectricoActionPerformed(evt);
            }
        });

        bActualizarAutoElectrico.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bActualizarAutoElectrico.setText("Actualizar");
        bActualizarAutoElectrico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActualizarAutoElectricoActionPerformed(evt);
            }
        });

        bEliminarAutoElectrico.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bEliminarAutoElectrico.setText("Eliminar");
        bEliminarAutoElectrico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEliminarAutoElectricoActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel10.setText("Duración de la bateria (Km):");

        tfDuracionBateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDuracionBateriaActionPerformed(evt);
            }
        });

        bConsultarAutoElectrico.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        bConsultarAutoElectrico.setText("Consultar");
        bConsultarAutoElectrico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConsultarAutoElectricoActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel13.setText("Número de puertas:");

        jLabel14.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel14.setText("Caballos de fuerza:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(bCrearAutoElectrico)
                        .addGap(18, 18, 18)
                        .addComponent(bActualizarAutoElectrico)
                        .addGap(18, 18, 18)
                        .addComponent(bEliminarAutoElectrico)
                        .addGap(18, 18, 18)
                        .addComponent(bConsultarAutoElectrico)
                        .addGap(0, 68, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfCaballosFuerza_AutoElectrico)
                            .addComponent(tfDuracionBateria)
                            .addComponent(tfNoPuerta_AutoElectrico))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(tfCaballosFuerza_AutoElectrico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNoPuerta_AutoElectrico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(tfDuracionBateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCrearAutoElectrico)
                    .addComponent(bActualizarAutoElectrico)
                    .addComponent(bEliminarAutoElectrico)
                    .addComponent(bConsultarAutoElectrico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addContainerGap())
        );

        tbTipoVehiculo.addTab("Auto Electrico", jPanel6);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Número de serie:");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Marca del vehiculo:");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Modelo:");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Color:");

        tfNoSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNoSerieActionPerformed(evt);
            }
        });

        tfMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMarcaActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Tipo de vehiculo:");

        cbTipoVehiculo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cbTipoVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Automovil", "Motocicleta", "Auto Electrico" }));
        cbTipoVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoVehiculoActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Año del vehiculo:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel15))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfMarca)
                    .addComponent(tfModelo)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfNoSerie)
                    .addComponent(jTextField1)
                    .addComponent(tfColor))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNoSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(53, 53, 53))
        );

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tbTipoVehiculo))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bSalir)
                .addGap(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(tbTipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfNoSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNoSerieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNoSerieActionPerformed

    private void bCrearMotocicletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearMotocicletaActionPerformed
        vehiculo = new Motocicleta();
        vehiculo.setNoSerie(tfNoSerie.getText());
        indice = crud.find(vehiculo);
        if (indice == -1) {
            vehiculo.setNoSerie(tfNoSerie.getText());
            vehiculo.setMarca(tfMarca.getText());
            vehiculo.setModelo(tfModelo.getText());
            vehiculo.setColor(tfColor.getText());
            ((Motocicleta) vehiculo).setPotencia(Float.parseFloat(tfPotencia.getText()));
            ((Motocicleta) vehiculo).setRodada(Byte.parseByte(tfRodada.getText()));
            crud.create(vehiculo);
        } else {
            JOptionPane.showMessageDialog(null, "Vehiculo existente");
            JOptionPane.showMessageDialog(null, crud.consultaInd(indice));
        }
        jTextAreaToMotocicleta.setText(crud.readMotocicleta() + "\n" + ((Motocicleta) vehiculo).combustible());
    }//GEN-LAST:event_bCrearMotocicletaActionPerformed

    private void tfDuracionBateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDuracionBateriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDuracionBateriaActionPerformed

    private void bActualizarMotocicletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualizarMotocicletaActionPerformed
        // TODO add your handling code here:
        vehiculo = new Motocicleta();
        vehiculo.setNoSerie(JOptionPane.showInputDialog("Número de serie: "));
        indice = crud.find(vehiculo);
        if (indice >= 0) {
            JOptionPane.showMessageDialog(null, crud.consultaInd(indice));
            vehiculo.setMarca(JOptionPane.showInputDialog("Nueva marca: "));
            vehiculo.setModelo(JOptionPane.showInputDialog("Nuevo modelo: "));
            vehiculo.setAnioModelo(Short.parseShort(JOptionPane.showInputDialog("Nuevo año del modelo: ")));
            vehiculo.setColor(JOptionPane.showInputDialog("Nuevo color: "));
            ((Motocicleta) vehiculo).setRodada(Byte.parseByte(JOptionPane.showInputDialog("Nueva Rodada: ")));
            ((Motocicleta) vehiculo).setPotencia(Float.parseFloat(JOptionPane.showInputDialog("Nueva Potencia: ")));
            jTextAreaToMotocicleta.setText(crud.readMotocicleta() + "\n" + ((Motocicleta) vehiculo).combustible());
            crud.update(vehiculo);
        } else {
            JOptionPane.showMessageDialog(null, "Vehiculo inexistente");
        }
    }//GEN-LAST:event_bActualizarMotocicletaActionPerformed

    private void bActualizarAutomovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualizarAutomovilActionPerformed
        vehiculo = new Automovil();
        vehiculo.setNoSerie(JOptionPane.showInputDialog("Número de serie: "));
        indice = crud.find(vehiculo);
        if (indice >= 0) {
            JOptionPane.showMessageDialog(null, crud.consultaInd(indice));
            vehiculo.setMarca(JOptionPane.showInputDialog("Nueva marca: "));
            vehiculo.setModelo(JOptionPane.showInputDialog("Nuevo modelo: "));
            vehiculo.setColor(JOptionPane.showInputDialog("Nuevo color: "));
            ((Automovil) vehiculo).setCaballosFuerza(Float.parseFloat(JOptionPane.showInputDialog("Caballos de fuerza: ")));
            ((Automovil) vehiculo).setNoPuertas(Byte.parseByte(JOptionPane.showInputDialog("Número de puertas: ")));
            crud.update(vehiculo);
        } else {
            JOptionPane.showMessageDialog(null, "Vehiculo inexistente");
        }
    }//GEN-LAST:event_bActualizarAutomovilActionPerformed

    private void bEliminarAutomovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarAutomovilActionPerformed
        int op = 0;
        vehiculo = new Automovil();
        vehiculo.setNoSerie(JOptionPane.showInputDialog("Número de serie: "));
        indice = crud.find(vehiculo);
        if (indice >= 0) {
            JOptionPane.showMessageDialog(null, crud.consultaInd(indice));
            op = JOptionPane.showConfirmDialog(null, "¿Está seguro de elimnar el registro?", "Confirmación", JOptionPane.YES_NO_OPTION);
            if (op == 0) {
                crud.delete(vehiculo);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Vehiculo inexistente");
        }
    }//GEN-LAST:event_bEliminarAutomovilActionPerformed

    private void bEliminarMotocicletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarMotocicletaActionPerformed
        // TODO add your handling code here:
        int op = 0;
        vehiculo = new Motocicleta();
        vehiculo.setNoSerie(JOptionPane.showInputDialog("Número de serie: "));
        indice = crud.find(vehiculo);
        if (indice >= 0) {
            JOptionPane.showMessageDialog(null, crud.consultaInd(indice));
            op = JOptionPane.showConfirmDialog(null, "¿Está seguro de elimnar el registro?", "Confirmación", JOptionPane.YES_NO_OPTION);
            if (op == 0) {
                crud.delete(vehiculo);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Vehiculo inexistente");
        }
    }//GEN-LAST:event_bEliminarMotocicletaActionPerformed

    private void bActualizarAutoElectricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualizarAutoElectricoActionPerformed
        // TODO add your handling code here:
        vehiculo = new AutoElectrico();
        vehiculo.setNoSerie(JOptionPane.showInputDialog("Número de serie: "));
        indice = crud.find(vehiculo);
        if (indice >= 0) {
            JOptionPane.showMessageDialog(null, crud.consultaInd(indice));
            vehiculo.setMarca(JOptionPane.showInputDialog("Nueva marca: "));
            vehiculo.setModelo(JOptionPane.showInputDialog("Nuevo modelo: "));
            vehiculo.setColor(JOptionPane.showInputDialog("Nuevo color: "));
            ((AutoElectrico) vehiculo).setCaballosFuerza(Float.parseFloat(JOptionPane.showInputDialog("Caballos de fuerza: ")));
            ((AutoElectrico) vehiculo).setNoPuertas(Byte.parseByte(JOptionPane.showInputDialog("Número de puertas: ")));
            ((AutoElectrico) vehiculo).setDuracionBateria(Float.parseFloat(JOptionPane.showInputDialog("Duracion de la bateria: ")));
            crud.update(vehiculo);
        } else {
            JOptionPane.showMessageDialog(null, "Vehiculo inexistente");
        }
    }//GEN-LAST:event_bActualizarAutoElectricoActionPerformed

    private void tfMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMarcaActionPerformed

    private void cbTipoVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoVehiculoActionPerformed
        bCrearAutomovil.setEnabled(true);
        bCrearMotocicleta.setEnabled(true);
        bCrearAutoElectrico.setEnabled(true);
        switch (cbTipoVehiculo.getSelectedIndex()) {
            case 0:
                tbTipoVehiculo.setEnabledAt(0, true);
                tfCaballosFuerza.setEnabled(true);
                tfNoPuertas.setEnabled(true);
                vehiculo = new Automovil();
                break;
            case 1:
                tbTipoVehiculo.setEnabledAt(1, true);
                tfPotencia.setEnabled(true);
                tfRodada.setEnabled(true);
                vehiculo = new Motocicleta();
                break;
            case 2:
                tbTipoVehiculo.setEnabledAt(2, true);
                tfCaballosFuerza.setEnabled(true);
                tfNoPuertas.setEnabled(true);
                tfDuracionBateria.setEnabled(true);
                vehiculo = new AutoElectrico();
                break;
        }
    }//GEN-LAST:event_cbTipoVehiculoActionPerformed

    private void bCrearAutomovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearAutomovilActionPerformed
        vehiculo = new Automovil();
        indice = crud.find(vehiculo);
        if (indice == -1) {
            vehiculo.setNoSerie(tfNoSerie.getText());
            vehiculo.setMarca(tfMarca.getText());
            vehiculo.setModelo(tfModelo.getText());
            vehiculo.setColor(tfColor.getText());
            ((Automovil) vehiculo).setCaballosFuerza(Float.parseFloat(tfCaballosFuerza.getText()));
            ((Automovil) vehiculo).setNoPuertas(Byte.parseByte(tfNoPuertas.getText()));
            crud.create(vehiculo);
        } else {
            JOptionPane.showMessageDialog(null, crud.consultaInd(indice));
            JOptionPane.showMessageDialog(null, crud.consultaInd(indice));
        }
        jTextAreaToAutomovil.setText(crud.readAutomovil() + "\n" + ((Automovil) vehiculo).combustible());
    }//GEN-LAST:event_bCrearAutomovilActionPerformed

    private void bConsultaAutomovilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConsultaAutomovilActionPerformed
        jTextAreaToAutomovil.setText(crud.readAutomovil() + "\n" + ((Automovil) vehiculo).combustible());
    }//GEN-LAST:event_bConsultaAutomovilActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        manejadorArchivo.escribirArchivo(crud.getGrupo(), crud.getIndice());
        System.exit(0);
    }//GEN-LAST:event_bSalirActionPerformed

    private void bConsultarMotocicletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConsultarMotocicletaActionPerformed
        jTextAreaToMotocicleta.setText(crud.readMotocicleta() + "\n" + ((Motocicleta) vehiculo).combustible());
    }//GEN-LAST:event_bConsultarMotocicletaActionPerformed

    private void bConsultarAutoElectricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConsultarAutoElectricoActionPerformed
        jTextAreaToAutoElectrico.setText(crud.readAutoElectrico() + "\n" + ((AutoElectrico) vehiculo).combustible());
    }//GEN-LAST:event_bConsultarAutoElectricoActionPerformed

    private void bCrearAutoElectricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCrearAutoElectricoActionPerformed
        // TODO add your handling code here:
        vehiculo = new AutoElectrico();
        vehiculo.setNoSerie(tfNoSerie.getText());
        indice = crud.find(vehiculo);
        if (indice == -1) {
            vehiculo.setNoSerie(tfNoSerie.getText());
            vehiculo.setMarca(tfMarca.getText());
            vehiculo.setModelo(tfModelo.getText());
            vehiculo.setColor(tfColor.getText());
            ((AutoElectrico) vehiculo).setCaballosFuerza(Float.parseFloat(tfCaballosFuerza_AutoElectrico.getText()));
            ((AutoElectrico) vehiculo).setNoPuertas(Byte.parseByte(tfNoPuerta_AutoElectrico.getText()));
            ((AutoElectrico) vehiculo).setDuracionBateria(Float.parseFloat(tfDuracionBateria.getText()));
            crud.create(vehiculo);
        } else {
            JOptionPane.showMessageDialog(null, "Vehiculo existente");
            JOptionPane.showMessageDialog(null, crud.consultaInd(indice));
        }
        jTextAreaToAutoElectrico.setText(crud.readAutoElectrico() + "\n" + ((AutoElectrico) vehiculo).combustible());
    }//GEN-LAST:event_bCrearAutoElectricoActionPerformed

    private void bEliminarAutoElectricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEliminarAutoElectricoActionPerformed
        // TODO add your handling code here:
        int op = 0;
        vehiculo = new AutoElectrico();
        vehiculo.setNoSerie(JOptionPane.showInputDialog("Número de serie: "));
        indice = crud.find(vehiculo);
        if (indice >= 0) {
            JOptionPane.showMessageDialog(null, crud.consultaInd(indice));
            op = JOptionPane.showConfirmDialog(null, "¿Está seguro de elimnar el registro?", "Confirmación", JOptionPane.YES_NO_OPTION);
            if (op == 0) {
                crud.delete(vehiculo);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Vehiculo existente");
        }
    }//GEN-LAST:event_bEliminarAutoElectricoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaAgencia.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaAgencia.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaAgencia.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaAgencia.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaAgencia().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bActualizarAutoElectrico;
    private javax.swing.JButton bActualizarAutomovil;
    private javax.swing.JButton bActualizarMotocicleta;
    private javax.swing.JButton bConsultaAutomovil;
    private javax.swing.JButton bConsultarAutoElectrico;
    private javax.swing.JButton bConsultarMotocicleta;
    private javax.swing.JButton bCrearAutoElectrico;
    private javax.swing.JButton bCrearAutomovil;
    private javax.swing.JButton bCrearMotocicleta;
    private javax.swing.JButton bEliminarAutoElectrico;
    private javax.swing.JButton bEliminarAutomovil;
    private javax.swing.JButton bEliminarMotocicleta;
    private javax.swing.JButton bSalir;
    private javax.swing.JComboBox<String> cbTipoVehiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextAreaToAutoElectrico;
    private javax.swing.JTextArea jTextAreaToAutomovil;
    private javax.swing.JTextArea jTextAreaToMotocicleta;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTabbedPane tbTipoVehiculo;
    private javax.swing.JTextField tfCaballosFuerza;
    private javax.swing.JTextField tfCaballosFuerza_AutoElectrico;
    private javax.swing.JTextField tfColor;
    private javax.swing.JTextField tfDuracionBateria;
    private javax.swing.JTextField tfMarca;
    private javax.swing.JTextField tfModelo;
    private javax.swing.JTextField tfNoPuerta_AutoElectrico;
    private javax.swing.JTextField tfNoPuertas;
    private javax.swing.JTextField tfNoSerie;
    private javax.swing.JTextField tfPotencia;
    private javax.swing.JTextField tfRodada;
    // End of variables declaration//GEN-END:variables

}
